version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: quimicanova_root
      MYSQL_DATABASE: quimicanova
      MYSQL_USER: quimicanova
      MYSQL_PASSWORD: quimicanova
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
